#!/bin/bash
mkdir tmp
cd tmp

export DSSSL=/usr/share/xml/docbook/stylesheet/nwalsh/xhtml/chunk.xsl

/usr/bin/xsltproc --stringparam html.stylesheet docbook.css ${DSSSL} ../book.xml

sed "s/{latest}/`date -u`/g" index.html >index.html.sed; mv index.html.sed index.html

mv *.html /home/neo/public_html/english/notes/

cd ..
rm -rf tmp

